language: cpp
cache: ccache

dist: focal
group: edge

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
    packages:
      - ninja-build
      - parallel
      - llvm-dev
      - clang
      - libomp5-12 # FIXME: as a recommended package of clang-12, why isn't this installed by default? Would like to get rid of packages with a version on develop
      - clang-format-11
      - libclang-dev

os:
  - linux

before_script:
  - ccache --zero-stats

after_script:
  - ccache --show-stats

script:
  - CLANG_FORMAT=clang-format-11 hack/fmt chk
  - LLVM_ROOT=/usr LDFLAGS=-fuse-ld=lld hack/hack gen Debug build
  - hack/hack test build
