language: cpp
cache: ccache

dist: focal
group: edge

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - ninja-build
      - parallel
      - llvm-dev
      - clang
      - clang-format
      - libclang-dev

os:
  - linux

before_script:
  - ccache --zero-stats

after_script:
  - ccache --show-stats

script:
  - CLANG_FORMAT=/usr/bin/clang-format hack/fmt chk
  - LLVM_ROOT=/usr LDFLAGS=-fuse-ld=lld hack/hack gen Debug build
  - hack/hack test build
